### PR TITLE
Small functionality to add a screenshot operation.

### PR DESCRIPTION
**Pull request by georgethomas111**
Added screen shot and looks like gofmt ran on client.go that pertained to the rest of the changes.

### CODE REVIEW

**Comment by georgethomas111** [comment]
@njasm Am not sure why the CI failed. Added one test to it which worked locally for me. Let me know if any changes need to be made for the PR if needed.

**Comment by njasm** [comment]
hi @georgethomas111 which version of firefox did you run the tests against that passed locally?

**Comment by georgethomas111** [comment]
Oops Sorry, Actually it was failing. 

Will update the Pr with the fix. :)

**Comment by njasm** [comment]
ok cool thanks :) 👍

**Comment by georgethomas111** [comment]
It was failing even without my commit in my local version. 

```
=== RUN   TestGetSessionCapabilities
[0,3,"getSessionCapabilities",null]
[1,3,null,{"capabilities":{"browserName":"Firefox","browserVersion":"47.0","platformName":"Darwin","platformVersion":"15.4.0","specificationLevel":0,"raisesAccessibilityExceptions":false,"rotatable":false,"acceptSslCerts":false,"takesElementScreenshot":true,"takesScreenshot":true,"proxy":{},"platform":"DARWIN","XULappId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","appBuildId":"20160604131506","device":"desktop","version":"47.0","command_id":2}}]
json: cannot unmarshal number into Go value of type string
--- FAIL: TestGetSessionCapabilities (0.00s)
```

**Comment by njasm** [comment]
yes found that bug it's on capability struct. now the specificationVersion have a uint32 value, and in older versions it was a string..

I've pushed to master the fix for that. it's passing : https://travis-ci.org/njasm/marionette_client/builds/138241678

can you pull my latests changes and merge them with your patch and run the tests now?

**Comment by georgethomas111** [comment]
Sure could do that. 👍

**Comment by njasm** [comment]
the patch is not passing, but that's ok, it's probably because of some erlier missed commit on my behalf or any clonflict resolving that when wrong.

Let's merge your code to master and i'll try to put it passing right now.

Thanks for the feature @georgethomas111 👍 
if you wanna keep helping please be my guest we still have a long way to support fully the marionette in gecko. :)

**Comment by georgethomas111** [comment]
It's somewhere in the protocol decode stage that the error is generated. I
want to fix it. Will send PR if I find a fix.

**Comment by njasm** [comment]
yes but that bug is only introduced after at lest one call to takeScreenshot. if we comment out that test, everything passes.. gonna look into it also. If I find anything, I'll keep you posted.

**Comment by georgethomas111** [comment]
Could you share the url where you are looking at specification of marionette client. I was hacking through looking at the python implementation and then attempting to mock it.

**Comment by njasm** [comment]
sure me too.. they don't have a spec around. I've already talked with the mozilla developers about it.

you can user they irc and go to the ATeam channel, or mostly work as I do, by checking the implementation of the marionette driver on mozilla repository and try to reverse it to create the client. :)

some resources:
https://dxr.mozilla.org/mozilla-central/source/testing/marionette/driver.js
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status

**Comment by njasm** [comment]
it seems that they are not returning the response structure that they protocol agrees on. they simply dumping the base64 encoded string of the screenshot.. and it breaks the decoder code..

**Comment by njasm** [comment]
MArionette bug tracking : https://bugzilla.mozilla.org/buglist.cgi?component=Marionette&product=Testing&bug_status=__open__

**Pull request merged**
